# This Dockerfile is for the main dev container that has access to all tools.
FROM mcr.microsoft.com/devcontainers/base:ubuntu-22.04

# Install Node.js, Python, Poetry, and Docker-in-Docker
USER root

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
    curl \
    git \
    gnupg \
    build-essential \
    libpq-dev \
    # Python dependencies
    python3.10 \
    python3-pip \
    python3.10-venv \
    # Docker-in-Docker
    apt-transport-https \
    ca-certificates \
    software-properties-common

# Install Node.js v18
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | python3.10 -

# Install Docker CLI
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
RUN echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
RUN apt-get update && apt-get install -y docker-ce-cli

# Create a non-root user
ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

# Add docker group and add user to it
RUN groupadd docker && usermod -aG docker $USERNAME

USER $USERNAME

# Add poetry to path
ENV PATH="/home/${USERNAME}/.local/bin:${PATH}"

# Install global node packages
RUN npm install -g pnpm migrate-mongo expo-cli

# Clean up
USER root
RUN apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*
USER $USERNAME