version: '3.8'

services:
  dev-container:
    image: mcr.microsoft.com/devcontainers/base:ubuntu-22.04
    volumes:
      - ..:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network
    command: /bin/sh -c "while sleep 1000; do :; done"
    user: vscode
    depends_on:
      - mongo
      - ollama

  server:
    build:
      context: ../server
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ../server:/usr/src/app
      - /usr/src/app/node_modules
      - ../shared:/usr/src/app/shared
    ports:
      - "4000:4000"
    env_file:
      - ../.env
    depends_on:
      - mongo
      - engine
      - ai-service
    networks:
      - app-network

  engine:
    build:
      context: ../engine
      dockerfile: Dockerfile
    command: poetry run uvicorn engine.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ../engine:/usr/src/app
      - ../shared:/usr/src/app/shared
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - mongo
    networks:
      - app-network

  ai-service:
    build:
      context: ../ai-service
      dockerfile: Dockerfile
    command: poetry run uvicorn ai_service.main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ../ai-service:/usr/src/app
      - ../shared:/usr/src/app/shared
    ports:
      - "8001:8001"
    env_file:
      - ../.env
    depends_on:
      - mongo
      - ollama
    networks:
      - app-network
  
  client:
    build:
      context: ../client
      dockerfile: Dockerfile.dev
    command: npm start
    volumes:
      - ../client:/usr/src/app
      - /usr/src/app/node_modules
      - ../shared:/usr/src/app/shared
    ports:
      - "8081:8081"
      - "19000-19002:19000-19002"
    networks:
      - app-network
    depends_on:
      - server

  mongo:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - app-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
  ollama-data:
